version: '3'

services:

    zookeeper:
        image: 'bitnami/zookeeper:latest'
        # ports:
        #     - '2181:2181'
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: 'bitnami/kafka:latest'
        hostname: 'kafka'
        # ports:
        #     - '9092:9092'
        depends_on:
            - zookeeper
        environment:
            - KAFKA_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes

    kafka-gui:
        image: tchiotludo/kafkahq
        # ports:
        #     - 8000:8080
        volumes:
            - ./.docker/config/application.yml:/app/application.yml
        depends_on:
            - kafka
